name: Deploy Logic App with Terraform

env:
  TF_LOG: DEBUG
  TF_VAR_ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  TF_VAR_ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  TF_VAR_COSMOS_DB_ACCOUNT: ${{ vars.COSMOS_DB_ACCOUNT }}  
  TF_VAR_COSMOS_DB_DATABASE: ${{ vars.COSMOS_DB_DATABASE }}
  TF_VAR_COSMOS_DB_CONTAINER: ${{ vars.COSMOS_DB_CONTAINER }}
  TF_VAR_COSMOS_DB_RG_NAME: "rg-logicappghdeploy-eus"
  TF_VAR_RG_LOCATION: ${{ vars.RG_LOCATION }}
  TF_VAR_RG_NAME: ${{ vars.RG_NAME }}
  TF_VAR_ENVIRONMENT: ${{ env.ENVIRONMENT_NAME }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: login
      uses: Azure/login@v2
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.8

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Plan Terraform
      run: terraform plan -no-color -input=false

    - name: Apply Terraform
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve